swagger: "2.0"
info:
  title: Book Management GraphQL API
  version: "1.0.0"

schemes:
  - https
produces:
  - application/json

paths:
  /search:
    post:
      summary: GraphQL endpoint for searching books
      operationId: searchBookGraphql
      consumes:
        - application/json
      parameters:
        - in: body
          name: query
          required: true
          schema:
            $ref: "#/definitions/GraphQLSearchRequest"
      responses:
        200:
          description: Query for searching books executed successfully
      x-google-backend:
        address: https://booksearch-m4slaxoduq-uc.a.run.app

  /delete:
    post:
      summary: GraphQL endpoint for deleting a book
      operationId: deleteBookGraphql
      consumes:
        - application/json
      parameters:
        - in: body
          name: mutation
          required: true
          schema:
            $ref: "#/definitions/GraphQLDeleteRequest"
      responses:
        200:
          description: Mutation for deleting a book executed successfully
      x-google-backend:
        address: https://books-backend-m4slaxoduq-uc.a.run.app/graphql

definitions:
  GraphQLSearchRequest:
    type: object
    required:
      - query
    properties:
      query:
        type: string

  GraphQLDeleteRequest:
    type: object
    required:
      - query
    properties:
      query:
        type: string
